server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    # widget.js 不缓存，确保接入方总能拿到最新版本
    location ~* \.js$ {
        add_header Cache-Control "no-cache, must-revalidate";
        add_header Access-Control-Allow-Origin *;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
